blank_issues_enabled: true
contact_links:
  - name: Vincoin Core Security Policy
    url: https://github.com/vincoin/vincoin/blob/master/SECURITY.md
    about: View security policy
  - name: Vincoin Core Developers
    url: https://vincoincore.org
    about: Vincoin Core homepage
