.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vincoin_qt test_vincoin_qt
clean: FORCE
	$(MAKE) -C .. vincoin_qt_clean test_vincoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_vincoin_qt_check
vincoin-qt vincoin-qt.exe: FORCE
	 $(MAKE) -C .. vincoin_qt
apk: FORCE
	$(MAKE) -C .. vincoin_qt_apk
