#ifndef VINCOIN_CHAINPARAMSSEEDS_H
#define VINCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the vincoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {0};

static const uint8_t chainparams_seed_test[] = {0};

#endif // VINCOIN_CHAINPARAMSSEEDS_H
